version: '3'
services:
  passwordapisrv1:
    image: nicopaez/password-api
  passwordapisrv2:
    image: nicopaez/password-api
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
